### ISSUE TITLE
Compiling with -Wall and GCC 4.8.1 throws warnings in scoped_ptr.h

### ISSUE THREAD

**Issue by GoogleCodeExporter** [Pluu/google-breakpad#534]
```
What steps will reproduce the problem?
1. Write code that includes client/linux/handler/exception_handler.h
2. Compile with GCC 4.8.1 and -Wall


What is the expected output? What do you see instead?
I expect no warnings, but I get this (actually this is with -Wall -Werror but 
either way):

.../breakpad/include/common/scoped_ptr.h: In destructor 
'google_breakpad::scoped_ptr<T>::~scoped_ptr()':
.../breakpad/include/common/scoped_ptr.h:74:18: error: typedef 
'type_must_be_complete' locally defined but not used 
[-Werror=unused-local-typedefs]
     typedef char type_must_be_complete[sizeof(T)];

Etc. for the other instances.

What version of the product are you using? On what operating system?
Version 1188
GNU/Linux Ubuntu 12.04 (with a locally-built GCC 4.8.1)

Please provide any additional information below.
I attached a patch, which just comments out the unused typedefs.
Note there are similar typedefs in the protobuf code, but unlike my own code 
when I compile breakpad I don't use -Werror so it is not fatal.
```

Original issue reported on code.google.com by `pds.mads...@gmail.com` on 1 Jun 2013 at 2:33

Attachments:
- [unused-typedef.patch](https://storage.googleapis.com/google-code-attachments/google-breakpad/issue-534/comment-0/unused-typedef.patch)
