### ISSUE TITLE
trunk read only failed to build on Ubuntu 12.04

### ISSUE THREAD

**Issue by GoogleCodeExporter** [Pluu/google-breakpad#492]
```
What steps will reproduce the problem?

1. $ svn checkout http://google-breakpad.googlecode.com/svn/trunk/ 
google-breakpad-read-only
2. $ cd google-breakpad-read-only
3. $ ./configure
4. $ make

What is the expected output? What do you see instead?

It should compile. 

I see:

/tmp/google-breakpad-read-only$ make
depbase=`echo src/client/linux/handler/exception_handler.o | sed 
's|[^/]*$|.deps/&|;s|\.o$||'`;\
        g++ -DHAVE_CONFIG_H -I. -I./src  -I./src   -Werror=non-virtual-dtor -Werror=vla -Werror=unused-variable -Werror=missing-braces -Werror=overloaded-virtual -g -O2 -MT src/client/linux/handler/exception_handler.o -MD -MP -MF $depbase.Tpo -c -o src/client/linux/handler/exception_handler.o src/client/linux/handler/exception_handler.cc &&\
        mv -f $depbase.Tpo $depbase.Po
src/client/linux/handler/exception_handler.cc:120:55: error: missing braces 
around initialiser for ‘sigaction’ [-Werror=missing-braces]
src/client/linux/handler/exception_handler.cc:120:55: error: missing braces 
around initialiser for ‘sigaction::<anonymous union>’ 
[-Werror=missing-braces]
src/client/linux/handler/exception_handler.cc: In member function ‘bool 
google_breakpad::ExceptionHandler::WriteMinidump()’:
src/client/linux/handler/exception_handler.cc:527:44: warning: ignoring return 
value of ‘int ftruncate(int, __off_t)’, declared with attribute 
warn_unused_result [-Wunused-result]
cc1plus: some warnings being treated as errors
make: *** [src/client/linux/handler/exception_handler.o] Error 1

/tmp/google-breakpad-read-only$ g++ --version
g++ (Ubuntu/Linaro 4.6.3-1ubuntu5) 4.6.3
Copyright (C) 2011 Free Software Foundation, Inc.


What version of the product are you using? 

Trunk


On what operating system?

Ubuntu 12.04.1 LTS


Please provide any additional information below.


```

Original issue reported on code.google.com by `aras.vai...@gmail.com` on 5 Sep 2012 at 11:31
